---
title: "Exploratory analysis"
author: "Jennah Gosciak"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
knit: (function(inputFile, encoding) { 
  rmarkdown::render(inputFile,
  encoding=encoding,
  output_file="01_analysis.html")})
output:
  html_document:
    toc: true
    theme: paper
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE, message = F, warning = F,
  fig.width = 6, fig.height = 10
)
```

```{r, setup2, include = F}
# Setup
library(renv)
library(tidyverse)
library(janitor)
library(magrittr)
library(eeptools)
library(assertr)
library(readr)
library(openxlsx)
library(DBI)
library(dplyr)
library(dbplyr)
library(RPostgres)
library(lubridate)
library(fs)
library(sf)
library(vroom)
library(leaflet)
library(haven)
library(geojsonsf)
library(s2)

source("99_common.R")
out <- "03_Output"
inp <- "01_Input"
fig_path <- path("03_Output", "figs")
web_path <- path("04_WebMap", "data")
spatial_path <- path("03_Output", "spatial_files")
colors <- c("#512e92","#e03616","#758ecd", "#FFC857","#0b5351")

# DB Connection
con <- dbConnect(Postgres(),
  user = "furmandata",
  password = rstudioapi::askForPassword(),
  host = "fcdata.c7h93yqbqnvu.us-east-1.rds.amazonaws.com",
  port = 5432,
  dbname = "fcdata",
  bigint = "integer"
)
```

# Analysis: 1998-2021

## Load cpi conversion factors
```{r, exp pluto}
# load cpi from bls
# method from: https://qrc.depaul.edu/oelguntillman/Winter12/Notes/7%20-%20CPI%20Notes.htm
cpi <- readxl::read_xlsx(path(inp, "r-cpi-u-rs-allitems.xlsx"),
                         skip = 5)
cpi

cpi_2020 <- cpi %>% 
  filter(YEAR == 2020) %>% 
  pull(AVG)

conversion_factors <- cpi %>% 
  filter(YEAR != 1977) %>% 
  mutate(conv = cpi_2020/AVG) %>% 
  rename(year = YEAR) %>% 
  select(year, conv)

conversion_factors
```


## NYU Assess Value Analysis
```{r}
drop_vars <- c("shape_area",
               "strgearea",
               "garagearea",
               "retailarea",
               "areasource",
               "otherarea",
               "landmark",
               "healtharea",
               "officearea",
               "ind_area",
               "comarea",
               "landmkdate",
               "factryarea",
               "areasource")

nyu_pts <- st_read(path(out, "nyu_allyrs_pts.geojson")) %>% 
  select(-any_of(drop_vars))%>%
  mutate(cd = ifelse(is.na(cd), cd2, cd),
         ownername = ifelse(is.na(ownername), str_trim(owner), str_trim(ownername))) %>% 
  mutate(borough = str_sub(cd, 1, 1)) %>% 
  select(-"cd2") %>% 
  verify(!is.na(borough)) %>% 
  filter(!(ownername %in% c("YOON, SOOK NYU", "YOON, SUK NYU", "ARA HOLDINGS OF NYU L",
                            "ARA HOLDINGS OF NYU LLC"))) %>% 
  filter(!(bbl == "3012920067")) %>% 
  # filter out polytechnic
  filter(!(str_detect(ownername, "POLYTECHNIC"))) %>% 
  mutate(bbl = case_when(bbl == "2057530140" ~ "2057520121",
                         TRUE ~ bbl)) %>% 
  mutate(address_form = case_when(!is.na(address) ~ address,
                                  TRUE ~ str_c(as.numeric(hnum_lo), str_name, "NEW YORK", "NEW YORK", zip, sep = ", ")))

nyu_poly <- st_read(path(out, "nyu_allyrs_upd.geojson")) %>% 
  unique() %>% 
  select(-any_of(drop_vars))%>%
  mutate(cd = ifelse(is.na(cd), cd2, cd)) %>% 
  mutate(borough = str_sub(cd, 1, 1)) %>% 
  select(-"cd2") %>% 
  verify(!is.na(borough)) %>% 
  filter(!(ownername %in% c("YOON, SOOK NYU", "YOON, SUK NYU", "ARA HOLDINGS OF NYU L",
                            "ARA HOLDINGS OF NYU LLC"))) %>% 
  # filter out random crown heights building
  filter(!(bbl == "3012920067")) %>% 
  # filter out polytechnic prior to 2008, when the formal affiliation with NYU began
  filter(!(str_detect(ownername, "POLYTECHNIC"))) %>%
  mutate(address_form = case_when(!is.na(address) ~ address,
                                  TRUE ~ str_c(as.numeric(hnum_lo), str_name, "NEW YORK", "NEW YORK", zip, sep = ", ")))

nyu_21 <- st_read(path(out, "nyu_21.geojson")) %>% 
  filter(!(ownername %in% c("YOON, SOOK NYU", "YOON, SUK NYU", "ARA HOLDINGS OF NYU L",
                            "ARA HOLDINGS OF NYU LLC"))) %>% 
  # filter out random crown heights building
  filter(!(bbl == "3012920067")) %>% 
  mutate(bbl = case_when(bbl == "2057530140" ~ "2057520121",
                         TRUE ~ bbl))

nyu_poly %>% 
  st_transform(4326) %>% 
  st_write(dsn = path(web_path, "nyu_allyrs.geojson"),
           delete_dsn = T,
           append = F)

# checking not missing year
nyu_poly %>% 
  as_tibble() %>% 
  verify(!is.na(year))

nyu_pts %>% 
  st_transform(4326) %>% 
  st_write(dsn = path(web_path, "nyu_allyrs_pts.geojson"),
           delete_dsn = T,
           append = F)
```

```{r}
url_boro <- "https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_Borough_Boundary/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson"
url_nhood <- "https://services5.arcgis.com/GfwWNkhOj9bNBqoJ/arcgis/rest/services/NYC_Neighborhood_Tabulation_Areas_2020/FeatureServer/0/query?where=1=1&outFields=*&outSR=4326&f=pgeojson"
url_streets <- "https://data.cityofnewyork.us/resource/m6hn-ddkx.geojson?$limit=200000"
url_roads <- "https://data.cityofnewyork.us/resource/gdww-crzy.geojson"
url_cds <- "https://data.cityofnewyork.us/resource/jp9i-3b7y.geojson?$limit=200000"
url_parks <- "https://data.cityofnewyork.us/resource/y6ja-fw4f.geojson?$limit=200000"

# load boros
boro <- st_read(url_boro) %>% 
  st_transform(2263)

# load major streets
# streets <- st_read(url_streets) %>% 
#   st_transform(2263)
# nrow(streets)

# load cds
cds <- st_read(url_cds)  %>% 
  st_transform(2263)

# load parks
parks <- st_read(url_parks) %>% 
  st_transform(2263)

# load nhood
nhood <- st_read(url_nhood)  %>% 
  st_transform(2263)

nyu_poly
```
## NYU in 2021
```{r}
# Identify list of community districts
intersecting_cds <- nyu_pts %>% 
  st_join(cds, join = st_intersects) %>% 
  filter(!is.na(boro_cd)) %>% 
  pull(boro_cd) %>% 
  unique()

# checking geometry works
# example of plot
nyu_poly %>% 
  filter(year == 2021) %>% 
  ggplot() +
  geom_sf(data = boro, color = "gray", fill = NA) +
  geom_sf(data = cds, color = "black", fill = NA, alpha = 0.5) +
  # geom_sf(data = streets %>% 
  #           st_crop(ext) %>% 
  #           select(c("post_type")), color = "gray", size = 1, fill = NA) +
  geom_sf(fill = colors[1], color = NA) +
  theme_void()

nyu_poly %>% 
  filter(year == 2021) %>% 
  as_tibble() %>% 
  pull(cd) %>% 
  unique()

nyu_poly %>% 
  filter(year == 2021) %>% 
  as_tibble() %>% 
  arrange(cd) %>% 
  select(c("cd", "bbl", "ownername", "address"), everything()) %>% 
  verify(!is.na(bldgarea))

nyu_poly %>% 
  filter(year == 2021) %>% 
  as_tibble() %>% 
  arrange(cd) %>% 
  select(c("cd", "bbl", "ownername", "address"), everything()) %>% 
  verify(!is.na(bldgarea)) %>% 
  group_by(cd) %>% 
  summarize(total_bldarea = sum(bldgarea),
            total_bld = n_distinct(bbl))

nyu_poly %>% 
  filter(year == 2021) %>% 
  as_tibble() %>% 
  arrange(cd) %>% 
  select(c("cd", "bbl", "ownername", "address"), everything()) %>% 
  verify(!is.na(bldgarea)) %>% 
  filter(address == "28 BETHUNE STREET" |
         address == "63 CHARLES STREET")

nyu_poly %>% 
  filter(year == 2021) %>% 
  as_tibble() %>% 
  arrange(cd) %>% 
  select(c("cd", "bbl", "ownername", "address"), everything()) %>% 
  verify(!is.na(bldgarea)) %>% 
  filter(cd == 307)
# 
# total_lotarea <- tbl(con, "mappluto_21v3") %>% 
#   filter(bldgclass %in% c("W5", "W6")) %>% 
#   summarize(total_lotarea = sum(lotarea, na.rm = T),
#             total_bldgarea = sum(bldgarea, na.rm = T)) %>% 
#   as_tibble()
# total_lotarea

nyu_21 %>% 
  as_tibble() %>% 
  summarize(nyu_lotarea = sum(lotarea, na.rm = T),
            nyu_bldgarea = sum(bldgarea, na.rm = T))
  
# nyu_21 %>% 
#   filter(bldgclass %in% c("W5", "W6")) %>% 
#   as_tibble() %>% 
#   summarize(nyu_lotarea = sum(lotarea, na.rm = T),
#             nyu_bldgarea = sum(bldgarea, na.rm = T)) %>% 
#   cbind(total_lotarea) %>% 
#   mutate(nyu_lotshare = nyu_lotarea * 100 / total_lotarea,
#          nyu_bldgshare = nyu_bldgarea * 100 / total_bldgarea)

nyu_21 %>% 
  filter(landuse %in% c("01", "02", "03", "04")) %>% 
  as_tibble() %>% 
  summarize(nyu_lotarea = sum(lotarea, na.rm = T),
            nyu_bldgarea = sum(bldgarea, na.rm = T))

nyu_21 %>% 
  filter(str_sub(bldgclass, 1, 1) == "I") %>% 
  as_tibble() %>% 
  summarize(nyu_lotarea = sum(lotarea, na.rm = T),
            nyu_bldgarea = sum(bldgarea, na.rm = T))

nyu_21 %>% 
  filter(bldgclass %in% c("W5", "W6")) %>% 
  as_tibble() %>% 
  pull(landuse) %>% 
  unique()

nyu_21 %>%
  summarize(assesstot = sum(assesstot, na.rm = T))
```

# Interactive map in leaflet
```{r}
nyu_leaflet <- st_transform(nyu_poly, 4263) %>% 
  filter(year == 1997) %>% 
  filter(!st_is_empty(.))

map_interactive <- leaflet(nyu_leaflet) %>%
  setView(lng = -73.9973, 
          lat = 40.7309, zoom = 14) %>% 
  addProviderTiles(provider = "CartoDB.DarkMatterNoLabels") %>% 
  addPolygons(color= "#9057FF", stroke = F,
              label = ~str_c(address, "\n", yearbuilt), fillOpacity = 1)
map_interactive
```

```{r}
# function to clip and export by cd in 2021
# programmatically exporting plots
expt_cd <- function(cds, shp, cd_num, yr) {
  cd_clip <- cds %>% 
    filter(boro_cd == cd_num)
  
  ext <- cd_clip %>% 
    st_bbox()
  
    
  cd_clip %>% 
    st_write(dsn = path(spatial_path, paste0("cd_", cd_num, ".geojson")),
             delete_dsn = T,
             append = F)
  
  shp %>% 
    filter(year == yr) %>% 
    st_join(cd_clip, join = st_intersects) %>%
    st_write(dsn = path(spatial_path, paste0("nyu_cd_", cd_num, "_", yr, ".geojson")),
             delete_dsn = T,
             append = F)
  
  # create an export plot
  nyu_poly %>% 
    filter(year == yr) %>% 
    ggplot() +
    geom_sf(data = streets %>% 
              st_crop(ext) %>% 
            select(c("post_type")), 
    color = "white", size = 0.5, fill = NA) +
    geom_sf(data = parks,
            fill = "#777777", color = NA) +
    geom_sf(fill = "#9057FF", color = NA) +
    geom_sf(data = cds, color = "blue", fill = NA, size = 3) +
    coord_sf(xlim = c(ext[1], ext[3]), ylim = c(ext[2], ext[4]),
             expand = F) +
    theme_void() +
    theme(plot.background = element_rect(fill = '#424242'))
    
  ggsave(path(fig_path, paste0("nyu_cd_", cd_num, "_", yr, ".pdf")))
}

# output all cds with nyu property in 2021
# walk(intersecting_cds, ~expt_cd(cds, nyu_poly, ., 2021))
```
```{r}
# nyu_21 %>% 
#   ggplot() +
#   geom_sf(data = streets,
#           color = "white", size = 0.01, alpha = 0.2, fill = NA) +
#   geom_sf(data = parks,
#             fill = "#777777", color = NA) +
#   geom_sf(fill = "#9057FF", color = NA) +
#   geom_sf(data = cds, color = "#777777", fill = NA, size = 0.1) +
#   theme_void() +
#   theme(
#     panel.border = element_blank(),
#     axis.text = element_blank(),
#     panel.grid = element_blank(),
#     axis.ticks = element_blank(),
#     plot.background = element_rect(fill = '#A5A5A5', color = NA),
#     panel.background = element_rect(fill = '#A5A5A5', color = NA)
#   )
# 
# ggsave(path(fig_path, "nyu_21_map.pdf"), height = 12.5, width = 24)
# #ggsave(path(fig_path, "nyu_21_map.png"), height = 12.5, width = 20)
```

## Map of Washington square park
```{r}
ggplot(nyu_21) +
  geom_sf(data = boro %>% 
            filter(BoroCode == 1), fill = NA, color = "white", size = 0.05) +
  geom_sf(data = parks %>% 
            filter(str_sub(parknum, 1, 1) == "M"), fill = "#777777", color = NA) +
  geom_sf(fill = "#9057FF", color = NA) +
  theme_void() +
  theme(plot.background = element_rect(fill = '#424242'))

ggsave(path(fig_path, "mn_map_nyu.pdf"), width = 9, height = 9)
```


## Produce summmary tables for 2021
```{r}
tbl1 <- nyu_21 %>% 
  summarize(bldgarea_nyu = sum(bldgarea, na.rm = T),
            lotarea_nyu = sum(lotarea, na.rm = T),
            assessval_nyu = sum(assesstot, na.rm = T),
            bbl_nyu = n_distinct(bbl))


# load 2021 pluto
# tbl1 <- tbl(con, "mappluto_21v3") %>% 
#   filter(!(ownertype %in% c("C", "O"))) %>% 
#   summarize(bldgarea_total = sum(bldgarea, na.rm = T),
#             lotarea_total = sum(lotarea, na.rm = T),
#             assessval_tot = sum(assesstot, na.rm = T),
#             bbl_tot = n_distinct(bbl)) %>% 
#   as_tibble() %>% 
#   cbind(tbl1) %>% 
#   mutate(bldgarea_per = round(bldgarea_nyu * 100/ bldgarea_total, 2),
#          lotarea_per = round(lotarea_nyu * 100 / bldgarea_total, 2),
#          assessval_per = round(assessval_nyu * 100 / assessval_tot, 2),
#          bbl_per = round(bbl_nyu * 100 / bbl_tot, 2))
# 
# tbl1

tbl1 %>%
  select(-c("bldgarea_total", "lotarea_total", "assessval_tot", "bbl_tot", "geometry")) %>% 
  pivot_longer(everything()) %>% 
  mutate(type = if_else(str_detect(name, "nyu"), "nyu", "per"),
         name = str_replace_all(name, "(_nyu)|(_per)", "")) %>% 
  pivot_wider(name, names_from = "type", values_from = "value") %>% 
  ggplot(aes(reorder(name, desc(per)), per)) +
  geom_col(fill = colors[1]) +
  geom_text(aes(label = nyu), vjust = -1) +
  theme_classic() +
  scale_y_continuous(limits = c(0, 3), breaks = c(0, 1, 2, 3)) +
  labs(x = "",
         y = "Percent of non-city owned properties")


ggsave(path(fig_path, "nyu_prop_summ.pdf"))
```

```{r}
# summary
# owner_summ <- tbl(con, "mappluto_21v3") %>% 
#   mutate(ownername = str_trim(str_remove_all(ownername, "[\\.,-:']")),
#          ownername = str_replace_all(ownername, "(CORP\\s|CORP$)", "CORPORATION")) %>% 
#   # filter out city and other public, state, or federal
#   filter(!(ownertype %in% c("C", "O"))) %>% 
#   # filter out unknown
#   filter(!(ownername %in% c("UNAVAILABLE OWNER", "NAME NOT ON FILE",
#                             "NATIONAL PARK SERVICE",
#                             "UNITED STATES OF AMERICA",
#                             "PORT AUTHORITY OF NY AND NJ",
#                             "UNITED STATES POSTAL SERVICE",
#                             "MTA  LIRR",
#                             "NYS DEPARTMENT OF TRANSPORTATION",
#                             "MTA  STATEN ISLAND RAILWAY",
#                             "HOUSING TRUST FUND CORPORATION",
#                             "NYC DEPARTMENT OF ENVIRONMENTAL PROTECTION",
#                             "NYS DIV OF LANDS AND FORESTS",
#                             "DORMITORY AUTHORITY OF THE STATE OF NEW YORK",
#                             "NYC TRANSIT AUTHORITY",
#                             "NYS DEPARTMENT OF ENVIRONMENTAL CONSERVATION",
#                             "CONSOLIDATED EDISON COOF NYINC",
#                             "NYC DEPARTMENT OF TRANSPORTATION",
#                             "CITY OF NEW YORK",
#                             "MTA METRO NORTH",
#                             "NYC HOUSING AUTHORITY",
#                             "METROPOLITAN TRANSPORTATION AUTHORITY",
#                             "HOUSING TRUST FUND CORP",
#                             "USPS",
#                             "NYS OFFICE OF GENERAL SERVICES",
#                             "MTA  METRO NORTH",
#                             "NYC HOUSING DEVELOPMENT CORPORATION"
#                             ))) %>% 
#   group_by(ownername) %>% 
#   summarize(bldgarea_total = sum(bldgarea, na.rm = T),
#             lotarea_total = sum(lotarea, na.rm = T),
#             assessval_tot = sum(assesstot, na.rm = T),
#             bbl_tot = n_distinct(bbl)) %>% 
#   ungroup() %>% 
#   arrange(desc(bldgarea_total))  %>% 
#   as_tibble()

# owner_summ_city <- tbl(con, "mappluto_21v3") %>% 
#   filter(!(ownername %in% c("UNAVAILABLE OWNER", "NAME NOT ON FILE"))) %>% 
#   group_by(ownername) %>% 
#   summarize(bldgarea_total = sum(bldgarea, na.rm = T),
#             lotarea_total = sum(lotarea, na.rm = T),
#             assessval_tot = sum(assesstot, na.rm = T),
#             bbl_tot = n_distinct(bbl)) %>% 
#   ungroup() %>% 
#   arrange(desc(bldgarea_total)) %>% 
#   as_tibble()

# Top ownership tables
owner_summ
owner_summ_city

owner_summ %>% 
  arrange(desc(bbl_tot))
```

## Graph of top ownership in NYC in 2021
```{r, fig.width = 10}
owner_summ %>% 
  head(10) %>% 
  mutate(owner_form = str_to_sentence(ownername),
         bldgarea_total = bldgarea_total / 1000) %>% 
  ggplot(aes(reorder(owner_form, bldgarea_total), bldgarea_total))+
  geom_col(fill = colors[1]) +
  geom_text(aes(label = round(bldgarea_total)), hjust = 1.2, color = "white") +
  coord_flip() +
  theme_classic() +
  scale_y_continuous(limits = c(0, 18000)) +
  labs(y = "Building sq. ft.",
       x = "")

ggsave(path(fig_path, "ranking_bldsqft.pdf"))

owner_summ %>%
  arrange(desc(bbl_tot)) %>% 
  head(10) %>% 
  mutate(owner_form = str_to_sentence(ownername)) %>% 
  ggplot(aes(reorder(owner_form, bbl_tot), bbl_tot))+
  geom_col(fill = colors[1]) +
  geom_text(aes(label = bbl_tot), hjust = 1.2, color = "white") +
  coord_flip() +
  theme_classic() +
  scale_y_continuous(limits = c(0, 180)) +
  labs(y = "Number of buildings",
       x = "")

ggsave(path(fig_path, "ranking_nbld.pdf"))
```
## Prep dat for interactive map
```{r}
# create a dataframe of the properties
nyu_df <- nyu_poly %>% 
  select(-any_of(drop_vars)) %>% 
  mutate(geom_point = geometry)

nyu_df

nyu_df %>% 
  filter(year == 1999)

nyu_df %>% 
  filter(bbl == "1009364222") %>% 
  as_tibble() %>% 
  select(c("year"), everything())
```
```{r}
# number of buildings by year
nyu_df %>% 
  group_by(year) %>% 
  summarize(count = n_distinct(bbl)) %>% 
  ggplot() +
  geom_line(aes(year, count)) +
  scale_x_continuous(limits = c(1998, 2021),
                     breaks = seq(1998, 2021, 3)) +
  theme_classic() +
  labs(x = "Year",
       y = "Number of buildings")

nyu_df %>% 
  filter(year == 2001) %>% 
  tablist_qc(ownername)
```

```{r}
# Class 4: All commercial and industrial properties, such as office, retail, factory buildings and all other properties not 
# included in tax classes 1, 2 or 3.

## Load tax rate
tax_rate <- read_csv(path(inp, "Property_Tax_Rates_by_Tax_Class.csv")) %>% 
  select(c("YEAR", "CLASS 4")) %>% 
  rename(year = YEAR) %>% 
  filter(!is.na(year)) %>% 
  mutate(rate = as.numeric(str_replace_all(`CLASS 4`, "%", ""))/100)
tax_rate
```

```{r}
# load assessed_value_avg
assessed_value_avg <- readRDS(path(out, "assess_value_averages.RDS"))

nrow(nyu_df)

nyu_assess_value <- nyu_df %>%
  mutate(borough = str_sub(cd, 1, 1),
           cd = as.numeric(cd)) %>% 
  left_join(conversion_factors, by = "year") %>% 
  left_join(assessed_value_avg, by = c("cd", "year")) %>% 
  left_join(tax_rate, by = "year") %>% 
  rowwise() %>%
  mutate(assessed_value_orig = max(assesstotl, 
                                   assesstota, 
                                   assesstot, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(taxes_calc = rate * assessed_value_orig) %>% 
  group_by(year) %>% 
  mutate(taxes_yr = sum(taxes_calc, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(bldgarea = case_when(is.na(bldgarea) | bldgarea == 0 ~ floorarea,
                              TRUE ~ as.double(bldgarea))) %>%
  mutate(assessed_value = if_else(is.na(bldgarea) | bldgarea == 0, 
                                  lotarea * avg_value_sqft,
                                  bldgarea * avg_value_sqft)) %>% 
  mutate(borough = recode(borough, "3" = "Brooklyn", "1" = "Manhattan",
                          "2" = "Bronx", "5" = "Staten Island",
                          "4" = "Queens")) %>% 
  mutate(assessed_adj = if_else(year < 2021,
                                round(assessed_value * conv),
                                assessed_value),
         assessed_adj_orig = if_else(year < 2021,
                                round(assessed_value_orig * conv),
                                assessed_value_orig),
         taxes_calc = if_else(year < 2021,
                              round(taxes_calc * conv),
                              taxes_calc),
         taxes_yr = if_else(year < 2021,
                            round(taxes_yr * conv),
                            taxes_yr))

nyu_assess_geo <- nyu_assess_value  %>% 
  st_transform(4326) %>%
  mutate(bldgarea = case_when(is.na(bldgarea) ~ floorarea,
                              TRUE ~ bldgarea)) %>% 
  select(
    "ownername", "year", "assessed_adj",
    "assessed_adj_orig",
    matches("area"),
    "cd",
    "address_form", "bbl", "borough",
    "taxes_yr", "taxes_calc", 
    matches("area")) %>% 
  mutate(across(c("assessed_adj",
                "assessed_adj_orig",
                "taxes_yr",
                "taxes_calc",
                "bldgarea"), ~if_else(is.na(.) | is.infinite(.), "", prettyNum(., big.mark = ",")))) %>% 
  mutate(across(c("address_form",
                "ownername"), ~if_else(is.na(.) | is.infinite(.), "", .))) %>% 
  mutate(across(c("assessed_adj",
                "assessed_adj_orig",
                "taxes_yr",
                "taxes_calc"), ~if_else(. != "", str_c("$",.), "")))

nyu_assess_geo %>% 
  filter(year == 2021) %>% 
  select(c("bbl", "ownername", "year"))
```

```{r}
library(geoclient)
geoms2geocode <- nyu_assess_geo %>% 
  filter(st_is_empty(geometry)) %>% 
  as_tibble() %>% 
  select(-"geometry")

geoms2geocode %>% 
  filter(is.na(address_form)) %>% 
  select(c("year", "bbl"))

geoms_geocoded <- geoms2geocode %>% 
  geo_search_data(address_form) %>% 
  rename(bbl_geo = bbl) %>%
  select(c("bbl_geo", "no_results")) %>% 
  cbind(geoms2geocode) %>% 
  filter(no_results == F) %>% 
  bind_rows(
    geoms2geocode %>% 
  filter(is.na(address_form))
  )  %>% 
  # need to manually code this bbl
  mutate(bbl = case_when(bbl == "2057530140" ~ "2057520121",
                         bbl != bbl_geo ~ bbl_geo,
                         TRUE ~ bbl))
geoms_geocoded

copy_to(con, geoms_geocoded,
  name = "geoms_geocoded", overwrite = T,
  temporary = T
)

fix_geom <- st_read(con, query = "SELECT g.*, m21.geom_poly as geom1,
                                          m2.geom_poly as geom2 FROM geoms_geocoded as g
                        LEFT JOIN mappluto_21v3 as m21 on (g.bbl = m21.bbl)
                        LEFT JOIN mappluto_02b as m2 on (g.bbl = m2.bbl)")

fix_geom %>% 
  as_tibble() %>% 
  st_set_geometry("geom2") %>% 
  filter(st_is_empty(geom2)) %>% 
  nrow() %>% 
  equals(0) %>% 
  stopifnot()

# rows are dropping, but I think that's to be expected?
# possibly condo vs. large building
fix_geom_filt <- fix_geom %>% 
  as_tibble() %>% 
  rename(geometry = geom2) %>% 
  st_set_geometry("geometry") %>%
  select(-c("geom1")) %>% 
  group_by(bbl, year) %>% 
  filter(row_number() == 1)
```

```{r}
nyu_assess_geo %>% 
  filter(!st_is_empty(geometry)) %>% 
  bind_rows(fix_geom_filt) %>% 
  filter(st_is_empty(geometry)) %>% 
  nrow() %>% 
  equals(0) %>% 
  stopifnot()
  
nyu_assess_geo %>% 
  filter(!st_is_empty(geometry)) %>% 
  bind_rows(fix_geom_filt) %>%   
  st_write(
    dsn = path(
      "04_WebMap",
      "data",
      "nyu_clean.geojson"
    ), driver = "GeoJSON",
    append = F,
    delete_dsn = T
  )
```
## Assessed value over time
```{r}
# assess value over time
nyu_assess_value %>% 
  group_by(borough, year) %>%
  summarize(avg_assessed_value = mean(assessed_value, na.rm = T)/1000) %>% 
  ggplot() +
  geom_line(aes(year, avg_assessed_value, color = borough)) +
  #scale_y_continuous(limits = c(0, 2000)) +
  theme_classic() +
  labs(x = "Year",
       y = "Average assessed value in thousands") +
  scale_color_manual(values = colors,
                     name = "Borough")

ggsave(path(fig_path, "assess_value1.png"))

nyu_assess_value %>% 
  group_by(borough, year) %>%
  filter(borough != "MN") %>% 
  summarize(avg_assessed_value = mean(assessed_value, na.rm = T)/1000) %>% 
  ggplot() +
  geom_line(aes(year, avg_assessed_value, color = borough)) +
  theme_classic() +
  labs(x = "Year",
       y = "Average assessed value in thousands") +
  scale_color_manual(values = colors,
                     name = "Borough")
ggsave(path(fig_path, "assess_value2.png"))

nyu_assess_value %>% 
  group_by(borough, year) %>%
  summarize(avg_assessed_value = mean(assessed_value_orig, na.rm = T)/1000) %>% 
  ggplot() +
  geom_line(aes(year, avg_assessed_value, color = borough)) +
  theme_classic() +
  labs(x = "Year",
       y = "Average assessed value in thousands") +
  scale_color_manual(values = colors,
                     name = "Borough")

ggsave(path(fig_path, "assess_value2.png"))
```
## Analysis of square footage (building or floor square footage)
```{r}
nyu_area <- nyu_pluto_app %>% 
  mutate(bldgarea = if_else(is.na(bldgarea), floorarea, as.double(bldgarea))) %>% 
  as_tibble() %>% 
  verify(!is.na(bldgarea)) %>% 
  group_by(borough, cd, year) %>%
  summarize(bldgarea_total = sum(bldgarea, na.rm = T)) %>% 
  group_by(borough, year) %>%
  mutate(bldgarea_total_boro = sum(bldgarea_total, na.rm = T)) %>% 
  rowwise() %>%
  mutate(bldgarea_share = round(bldgarea_total * 100 / bldgarea_total_boro)) %>% 
  ungroup() %>% 
  mutate(across(c("bldgarea_total", "bldgarea_total_boro"), ~./1000)) %>% 
  mutate(borough = recode(borough, "BK" = "Brooklyn", "MN" = "Manhattan",
                          "BX" = "Bronx", "SI" = "Staten Island",
                          "QN" = "Queens"))

nyu_area %>% 
  select(c("borough", "year", "bldgarea_total_boro")) %>% 
  unique() %>% 
  ggplot() +
  geom_line(aes(year, bldgarea_total_boro, color = borough)) +
  theme_classic() +
  labs(x = "Year",
       y = "Square feet in thousands") +
  scale_color_manual(values = colors)
ggsave(path(fig_path, "area_1.pdf"))

nyu_area %>% 
  filter(borough == "Manhattan" | borough == "Brooklyn") %>% 
  select(c("borough", "year", "bldgarea_total_boro")) %>% 
  unique() %>% 
  ggplot() +
  geom_line(aes(year, bldgarea_total_boro, color = borough)) +
  theme_classic() +
  labs(x = "Year",
       y = "Square feet in thousands") +
  scale_color_manual(values = colors)
ggsave(path(fig_path, "area_2.pdf"))
```

```{r}
# investigating dip in square footage
nyu_pluto_app %>% 
  filter(year == 2012) %>% 
  as_tibble() %>% 
  anti_join(nyu_pluto_app %>%
              filter(year == 2015) %>% 
              as_tibble(), by = "bbl") %>% 
  select(c("bbl"), everything())

tbl(con, "mappluto_12v2") %>% 
  filter(bbl == "1005400024") %>% 
  select(c("ownername"), everything())

tbl(con, "mappluto_15v1") %>% 
  filter(bbl == "1005400024") %>% 
  select(c("ownername", "bldgarea"), everything())
```




